### ISSUE TITLE
HTML directives with dashes do not highlight correctly

### ISSUE THREAD

**Issue by austinpray** [digitaltoad/vim-jade#57]
![screenshot 2015-01-08 17 34 41](https://cloud.githubusercontent.com/assets/2192970/5673040/bbd5f242-975c-11e4-8d56-2724ddc86e77.png)

I expected it to look like:

![screenshot 2015-01-08 17 35 49](https://cloud.githubusercontent.com/assets/2192970/5673046/cc7db6ac-975c-11e4-81fc-ebbb39d051fb.png)

With the blue braces around the arguments parenthesis

**Comment by digitaltoad** [comment]
What colorscheme is this?

**Comment by austinpray** [comment]
It's http://ethanschoonover.com/solarized

It's pretty popular. Does the highlighting work for you in other themes?

**Comment by digitaltoad** [comment]
See https://github.com/digitaltoad/vim-jade/pull/61
