### ISSUE TITLE
plugin does not do anything

### ISSUE THREAD

**Issue by cmickelsonO1** [digitaltoad/vim-jade#60]
using vim7.4 with Vundle, here is my .vimrc https://gist.github.com/cmickelsonO1/e2ea58caa8905c2c07d3

**Comment by digitaltoad** [comment]
Can you try moving
```vim
filetype plugin on
filetype indent on
filetype plugin indent on 
"...
syntax on
syntax enabled
```
to the bottom of your vimrc.

**Comment by cmickelsonO1** [comment]
moved lines to the bottom of the file.... doesnt look like that is the issue. Also tried removing vim-jade, and installing with git clone thinking maybe there was something wrong with the vundle plugin, this is also not effecting the vim-jade plugin, It doesnt look as if any other plugins are failing, should I try a previous version on vim-jade?. Any other possible issues?
________________________________

**Comment by digitaltoad** [comment]
My thought is the filetype is not executing properly. Can you run a ```:set ft=jade``` on a jade file.

**Comment by cmickelsonO1** [comment]
That works
________________________________

**Comment by digitaltoad** [comment]
I run into this issue most with Vundle users. I haven't found the clear answer other than adding a autocmd  for jade files. I personally do not use Vundle, but instead, Pathogen. I would like to get this issue figured out, but I have a feeling its an issue on the Vundle side as many people have filetype issues.

**Comment by digitaltoad** [comment]
I did just create a new setup using your vimrc and a blank .vim directory other than vundle and had no problems. This https://github.com/gmarik/Vundle.vim/issues/176 says that you should disable filetype before vundle and enable it afterwards.

**Comment by cmickelsonO1** [comment]
Thanks for the help, I will try messing around with disabling/enabling filetype, and maybe switch over to pathogen.
________________________________
