### ISSUE TITLE
Block Expansion is not highlighted

### ISSUE THREAD

**Issue by SquidEpps** [digitaltoad/vim-jade#63]
> To save space, jade provides an inline syntax for nested tags. (http://jade-lang.com/reference/tags/)

Expected:
![screen shot 2015-03-10 at 8 32 48](https://cloud.githubusercontent.com/assets/5869509/6569689/102ec878-c700-11e4-819b-e90fa7934bb2.png)

Got:
![screen shot 2015-03-10 at 8 29 58](https://cloud.githubusercontent.com/assets/5869509/6569701/2df33e02-c700-11e4-9421-732dfdb849b8.png)

Text after the first tag is marked as `jadeTagInlineText`

**Comment by digitaltoad** [comment]
I haven't had a chance to look into this yet, but I haven't forgot about it.

—
Josh

**Comment by digitaltoad** [comment]
Is this still an issue? In your image, I don't think `div.content : img.icon` is accepted syntax as this would just produce `<div class="content">: img.icon</div>`

**Comment by SquidEpps** [comment]
My bad. Didn't notice that space before the colon. If you remove it than syntax becomes valid and is highlighted correctly. So, this is not an issue anymore.
