### ISSUE TITLE
Highlighting makes vim  slow

### ISSUE THREAD

**Issue by ianks** [digitaltoad/vim-jade#67]
When I have jade.vim enabled, cursor movement becomes extremely slow. I profiled my session, and it seems `OnCursorMoved` was the most expensive operation. I am not sure what is causing this, but I have never experienced this issue with other syntax highlighting plugins.

The next slowest call is HighlightMatchingPair. I imagine there might be a slow regex somewhere causing highlighting with a pair to be slow. I am not familiar with VIM syntax files, do you have any ideas about this?

**Comment by digitaltoad** [comment]
Take a look at https://github.com/digitaltoad/vim-jade/issues/33 and let me know if that helps.



—
Josh
