### ISSUE TITLE
More modern HTML5 semantic tags are not recognized as valid keywords.

### ISSUE THREAD

**Issue by kindaro** [digitaltoad/vim-jade#69]
![2015-08-01-042508_104x57_scrot](https://cloud.githubusercontent.com/assets/2599460/9020150/71ea54bc-3805-11e5-8d8e-c1183fce5a5c.png)
I hope the picture makes it clear.

1. Tags such as a4 get highlighted. I get it's cause they're valid keywords.
2. Tags such as a8 don't. I get it's since they're not.
3. Tags such as header, article don't get highlighted. They should.

Please help me understand how the word is to be recognized as keyword so I could fix and submit pull request. Thank you for your time!

**Comment by digitaltoad** [comment]
If you use https://github.com/othree/html5.vim this will be automatic.
