### ISSUE TITLE
support for multiple inline elements

### ISSUE THREAD

**Issue by acidjazz** [digitaltoad/vim-jade#74]
```jade
.div1: .div2
```

comes out as

![image](https://cloud.githubusercontent.com/assets/967369/11018098/8cf28774-856d-11e5-80f6-eabbb6bcd0d6.png)

**Comment by digitaltoad** [comment]
This is actually partially working but not with implicit div via class. Something like `div.content: div.inner` will highlight correctly. I'll look into it.
